x-common-config:
  &common-config
  network_mode: host
  ipc: host 
  pid: host
  restart: unless-stopped
  environment:
    - FASTRTPS_DEFAULT_PROFILES_FILE=/shm-only.xml

services:
  luxonis:
    image: husarion/depthai:humble-2.8.1-20240127
    <<: *common-config
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./oak-1-low-bandwidth.yaml:/params.yaml
    device_cgroup_rules:
      - 'c 189:* rmw'
    command: >
      ros2 launch depthai_ros_driver camera.launch.py
        params_file:=/params.yaml
        parent_frame:=camera_mount_link

  rplidar:
    image: husarion/rplidar:humble-1.0.1-20240216
    <<: *common-config
    devices:
      - ${LIDAR_SERIAL:-/dev/ttyRPLIDAR}:/dev/ttyUSB0
    command: >
      ros2 launch /husarion_utils/rplidar.launch.py
        serial_baudrate:=${LIDAR_BAUDRATE:-256000}
        serial_port:=/dev/ttyUSB0
