name: rosbot-xl
adopt-info: rosbot-xl
license: Apache-2.0
summary: A driver for ROSbot XL mobile robot
icon: snap/gui/rosbot-xl.png
description: |
  The **rosbot-xl** snap includes all the essential software required to operate the ROSbot XL, including the controller, robot state publisher, and more.
  
  **Installation**

  To install this snap on the Single Board Computer (SBC) within the ROSbot XL chassis, follow these steps:

  1. Connect the SBC to the Digital Board inside ROSbot XL using an Ethernet cable.
  2. Configure the Ethernet Interface with the static IP address `192.168.77.2` (port `8888` on this IP is used by the STM32F4 microcontroller).
  3. Run the following command to install the snap:

     snap install rosbot-xl

  **Parameters**

  The snap provides the following configurable parameters (`param name`: `default value`):

  * `driver`: `{...}`
  * `ros-domain-id`: `0` - Sets the `ROS_DOMAIN_ID` environment variable for the ROS driver.
  * `ros-localhost-only`: `0` - Sets the `ROS_LOCALHOST_ONLY` environment variable for the ROS driver.
  * `serial-port`: `auto` - Configures the serial port for firmware updates (e.g., `/dev/ttyUSB0`), or set it to `auto`.
  * `transport`: `udp` - Configures DDS transport. Options are `udp`, `shm`, `builtin`. Corresponding DDS XML files can be found in the `/var/snap/rosbot-xl/common` directory (custom FastDDS setups can also be created here).
  * `webui`: `{...}`

  The `driver` parameter is a dictionary containing the following keys for a ROS 2 driver:

  * `driver.namespace`: `(unset)` - Namespace for all topics and transforms.
  * `driver.mecanum`: `True` - Enables the mecanum drive controller; otherwise, uses the differential drive controller.
  * `driver.include-camera-mount`: `True` - Includes the camera mount in the robot URDF.
  * `driver.camera-model`: `None` - Adds the camera model to the robot URDF.
  * `driver.lidar-model`: `None` - Adds the LIDAR model to the robot URDF.

  The `webui` parameter is a dictionary containing the following keys for the Web UI:

  * `webui.layout`: `default` - Specifies the layout for the Web UI. Available `*.json` layout files can be found in the `/var/snap/rosbot-xl/common` directory (custom layouts can also be created here).
  * `webui.port`: `8080` - Specifies the port for the built-in web server hosting the Web UI.

  To set parameters, use the snap set command, e.g.,

     snap set rosbot-xl driver.mecanum=True

  **Available Apps (Main)**

  * `rosbot-xl.flash` - Flash firmware for the STM32F4 microcontroller.
  * `rosbot-xl.start` - Start the daemon running the ROSbot XL ROS 2 driver.
  * `rosbot-xl.stop` - Stop the daemon running the ROSbot XL ROS 2 driver.
  * `rosbot-xl.start-web-ui` - Start the daemon running the Web UI (available at `http://<ROBOT_IP>:8080/ui` by default).
  * `rosbot-xl.stop-web-ui` - Stop the daemon running the Web UI.
  * `rosbot-xl.teleop` - Run the `teleop_twist_keyboard` node to control the robot from a terminal.

  **Auxiliary Apps**

  * `rosbot-xl.config-ftdi` - Set up the CBUS pins in the FTDI chip (used with RST and BOOT0 pins in STM32); needs to be done only once.
  * `rosbot-xl.print-serial-number` - Print the CPU ID and serial number of ROSbot XL.
  * `rosbot-xl.reset-stm32` - Reset the STM32F4 microcontroller.

  **Working with ROS Parameters**

  For multiple snaps running ROS 2 or host-snap-Docker communication, useful files and scripts are available in `/var/snap/rosbot-xl/common/`.

  Example usage:

     # Set parameters in the rosbot-xl snap
     sudo snap set rosbot-xl transport=udp ros-domain-id=123 driver.namespace=abc

     # Mirror the setup for other ROS 2 snaps
     sudo snap set husarion-depthai $(cat /var/snap/rosbot-xl/common/ros_snap_args)
     sudo snap set husarion-rplidar $(cat /var/snap/rosbot-xl/common/ros_snap_args)

     # Set up the current shell with the same configurations
     source /var/snap/rosbot-xl/common/ros.env

     # Install configurations with
     /var/snap/rosbot-xl/common/manage_ros_env.sh
     # After changing rosbot-xl parameters, open a new terminal, or run:
     source ~/.bashrc

     ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args --remap __ns:=/${ROS_NAMESPACE}

# Additional info:
#   **Notes**

#   * `rosbot-xl.daemon` runs as the `root` user. To enable shared-memory communication (`ros-localhost-only=1` or `transport` set to `shm` or `builtin`), ensure the user on the host (or in Docker) is also `root`.
#   * To run the ROS 2 driver in the current terminal session (and enable shared memory communication with a non-root user):

#      sudo rosbot-xl.stop
#      rosbot-xl

#   * Display logs from the ROS 2 node with:

#      sudo snap logs rosbot-xl.daemon

#   * Display logs from the snap logger with:
     
#      journalctl -t rosbot-xl

#   * `rosbot-xl` snap by default uses the following ports: `3000` by the safe-shutdown service, `8888` by microROS Agent, `8080` by a Web UI.

grade: stable
confinement: strict
base: core22

contact: https://github.com/husarion/rosbot-xl-snap/issues
issues: https://github.com/husarion/rosbot-xl-snap/issues
website: https://husarion.com/manuals/rosbot-xl/overview/

architectures:
  - build-on: amd64
    build-for: amd64
  # - build-on: amd64
  #   build-for: arm64
  - build-on: arm64
    build-for: arm64

slots:
  shm-slot:
    interface: shared-memory
    write: ['*'] # paths are relative to /dev/shm

plugs:
  shm-plug:
    interface: shared-memory
    shared-memory: shm-slot
    private: false

apps:

  daemon:
    command: usr/bin/launcher.sh
    command-chain: [usr/bin/ros_setup.sh]
    daemon: simple
    install-mode: enable
    plugs: [network, network-bind, shm-plug]
    slots: [shm-slot]
    extensions: [ros2-humble-ros-base]

  db-server:
    command: usr/bin/db_server_launcher.sh
    daemon: simple
    install-mode: enable
    plugs: [network, network-bind, shutdown]

  rosbot-xl:
    command: usr/bin/launcher.sh
    command-chain: [usr/bin/check_daemon_running.sh, usr/bin/ros_setup.sh]
    plugs: [network, network-bind, shm-plug]
    slots: [shm-slot]
    extensions: [ros2-humble-ros-base]

  flash:
    command: usr/bin/flash_launcher.sh
    plugs: [raw-usb, network-bind]
    extensions: [ros2-humble-ros-base]

  teleop:
    command: usr/bin/teleop_launcher.sh
    command-chain: [usr/bin/ros_setup.sh]
    plugs: [network, network-bind, shm-plug]
    slots: [shm-slot]
    extensions: [ros2-humble-ros-base]

  print-serial-number:
    command: usr/bin/serial_number_launcher.sh
    command-chain: [usr/bin/ros_setup.sh]
    plugs: [network, network-bind, shm-plug]
    slots: [shm-slot]
    extensions: [ros2-humble-ros-base]

  start:
    command: usr/bin/start_launcher.sh

  stop:
    command: usr/bin/stop_launcher.sh

  reset-stm32:
    command: usr/bin/reset_stm32_launcher.sh
    plugs: [raw-usb, network-bind]

  config-ftdi:
    command: usr/bin/ftdi_eeprom_conf_launcher.sh
    plugs: [raw-usb, network-bind]

  web-ui:
    command: usr/bin/caddy_launcher.sh
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

  web-ws:
    command: usr/bin/bridge_launcher.sh
    command-chain: [usr/bin/ros_setup.sh]
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind, shm-plug]
    slots: [shm-slot]
    extensions: [ros2-humble-ros-base]

  start-web-ui:
    command: usr/bin/start_web_ui_launcher.sh

  stop-web-ui:
    command: usr/bin/stop_web_ui_launcher.sh

parts:
  rosbot-xl:
    plugin: colcon
    source: https://github.com/husarion/rosbot_xl_ros.git
    source-branch: "0.11.4"
    build-packages: 
      - python3-vcstool
    stage-packages: 
      - stm32flash
      - libusb-1.0-0
      - usbutils
      - ros-humble-rmw-cyclonedds-cpp
    override-pull: |
      craftctl default

      vcs import $CRAFT_PART_SRC < $CRAFT_PART_SRC/rosbot_xl/rosbot_xl_hardware.repos
      cp -r $CRAFT_PART_SRC/ros2_controllers/diff_drive_controller $CRAFT_PART_SRC/
      cp -r $CRAFT_PART_SRC/ros2_controllers/imu_sensor_broadcaster $CRAFT_PART_SRC/
      rm -rf $CRAFT_PART_SRC/ros2_controllers
      rm -r $CRAFT_PART_SRC/rosbot_xl_gazebo
      # Ignore so that rosdep doesn't pull deps
      # and colcon doesn't build
      # touch $CRAFT_PART_SRC/rosbot_xl_gazebo/COLCON_IGNORE

      # Set the snap version from the git tag
      # The grade is set to 'stable' if the latest entry in the git history
      # is the tag itself, otherwise set to devel
      version="$(git describe --always --tags| sed -e 's/^v//;s/-/+git/;y/-/./')"
      [ -n "$(echo $version | grep "+git")" ] && grade=devel || grade=stable
      craftctl set version="$version"
      craftctl set grade="$grade"

  # rosbot-xl:
  #   plugin: colcon
  #   source: https://github.com/husarion/rosbot_xl_manipulation_ros.git
  #   # source-branch: "0.11.0"
  #   build-packages: 
  #     - python3-vcstool
  #   stage-packages: 
  #     - stm32flash
  #     - libusb-1.0-0
  #     - usbutils
  #   override-pull: |
  #     craftctl default

  #     vcs import $CRAFT_PART_SRC < $CRAFT_PART_SRC/rosbot_xl_manipulation/rosbot_xl_manipulation.repos
  #     vcs import $CRAFT_PART_SRC < $CRAFT_PART_SRC/rosbot_xl_ros/rosbot_xl/rosbot_xl_hardware.repos
  #     vcs import $CRAFT_PART_SRC < $CRAFT_PART_SRC/open_manipulator_x/open_manipulator_x.repos

  #     cp -r $CRAFT_PART_SRC/ros2_controllers/diff_drive_controller $CRAFT_PART_SRC/
  #     cp -r $CRAFT_PART_SRC/ros2_controllers/imu_sensor_broadcaster $CRAFT_PART_SRC/
  #     rm -rf $CRAFT_PART_SRC/ros2_controllers
  #     rm -r $CRAFT_PART_SRC/rosbot_xl_ros/rosbot_xl_gazebo
  #     rm -r $CRAFT_PART_SRC/rosbot_xl_manipulation_gazebo
  #     # Ignore so that rosdep doesn't pull deps
  #     # and colcon doesn't build
  #     # touch $CRAFT_PART_SRC/rosbot_xl_gazebo/COLCON_IGNORE

  #     # Set the snap version from the git tag
  #     # The grade is set to 'stable' if the latest entry in the git history
  #     # is the tag itself, otherwise set to devel
  #     version="$(git describe --always --tags| sed -e 's/^v//;s/-/+git/;y/-/./')"
  #     [ -n "$(echo $version | grep "+git")" ] && grade=devel || grade=stable
  #     craftctl set version="$version"
  #     craftctl set grade="$grade"

  teleop:
    plugin: nil
    stage-packages:
      - ros-humble-teleop-twist-keyboard
      - ros-humble-teleop-twist-joy

  # web-ui:
  #   plugin: nil
  #   build-packages:
  #     - curl
  #   build-environment:
  #     - CADDY_RELEASE: "2.7.4"
  #   override-build: |
  #     set -x
  #     craftctl default
  #     curl -L https://github.com/caddyserver/caddy/releases/download/v${CADDY_RELEASE}/caddy_${CADDY_RELEASE}_linux_${CRAFT_ARCH_BUILD_FOR}.deb -o caddy.deb
  #     dpkg -i caddy.deb

  web-server:
    plugin: dump
    source: 
      - on amd64: https://github.com/caddyserver/caddy/releases/download/v2.7.4/caddy_2.7.4_linux_amd64.deb
      - on arm64: https://github.com/caddyserver/caddy/releases/download/v2.7.4/caddy_2.7.4_linux_arm64.deb
    source-type: deb

  web-ui:
    plugin: nil
    build-packages:
      - curl
    override-build: |
      # Use the Snapcraft build directory which is writable
      cd $SNAPCRAFT_PART_BUILD
      curl -L https://github.com/husarion/foxglove-studio/releases/download/v1.0.1/web-build.tar.gz -o foxglove.tar.gz
      mkdir -p www/foxglove
      tar -xzf foxglove.tar.gz -C www/foxglove
      rm foxglove.tar.gz
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/local
      cp -r www $SNAPCRAFT_PART_INSTALL/usr/local

  web-ws:
    plugin: nil
    stage-packages:
      - ros-humble-foxglove-bridge
      - ros-humble-rosbridge-server
      - ros-humble-bond
      - ros-humble-control-msgs
      - ros-humble-controller-manager-msgs
      - ros-humble-image-transport-plugins
      - ros-humble-map-msgs
      - ros-humble-nav2-msgs
      - ros-humble-tf2-msgs
      - ros-humble-robot-localization

  yq:
    plugin: nil
    override-build: |
      craftctl default

      YQ_VERSION="v4.35.1"
      TARGETARCH=$CRAFT_ARCH_BUILD_FOR
      curl -L "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${TARGETARCH}" -o $CRAFT_PART_BUILD/yq
    override-prime: |
      craftctl default
    
      cp $CRAFT_PART_BUILD/yq $CRAFT_PRIME/usr/bin/yq
      chmod +x $CRAFT_PRIME/usr/bin/yq
    build-packages:
      - curl

  db-server:
    plugin: nil
    stage-packages:
      - dbus
      - curl
      - netcat

  pip3-dependencies:
    plugin: python
    source: .
    build-packages:
      - python3-pip
    python-packages:
      - pyftdi

  # copy local scripts to the snap usr/bin
  local-files-ros:
    plugin: dump
    source: snap/local/ros_common/
    organize:
      '*.sh': usr/bin/
      '*.xml': usr/share/rosbot-xl/config/

  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
      '*.py': usr/bin/
      '*.yaml': usr/share/rosbot-xl/config/
      '*.xml': usr/share/rosbot-xl/config/
      '*.json': usr/share/rosbot-xl/config/
      'Caddyfile': usr/share/rosbot-xl/config/
