#!/bin/sh -e

# Define a function to log messages
log() {
  local message="$1"
  # Log the message with logger
  logger -t "${SNAP_NAME}" "install hook: $message"
}


# Parameters are 'unset'.
# Default configuration values is left to the launch file.
snapctl set driver.mecanum=True
snapctl set driver.include-camera-mount=True
snapctl set driver.camera-model!
snapctl set driver.lidar-model!
snapctl set driver.namespace! # unset
snapctl set webui.layout=foxglove-default.json
snapctl set serial-port="/dev/ttyUSBDB"
snapctl set transport="udp"
snapctl set ros-localhost-only=0
snapctl set ros-domain-id=0

if ! snapctl is-connected ros-humble-ros-base; then
  log "Plug 'ros-humble-ros-base' isn't connected, please run:"
  log "sudo snap connect ${SNAP_NAME}:ros-humble-ros-base ros-humble-ros-base:ros-humble-ros-base"
fi

if ! snapctl is-connected shm-plug; then
  log "Plug 'shm-plug' isn't connected, please run:"
  log "sudo snap connect ${SNAP_NAME}:shm-plug ${SNAP_NAME}:shm-slot"
fi

if ! snapctl is-connected raw-usb; then
  log "Plug 'raw-usb' isn't connected, please run:"
  log "sudo snap connect ${SNAP_NAME}:raw-usb"
fi

# copy meshes to shared folder
log "copy meshes to '${SNAP_COMMON}/ros2_ws/'"
mkdir -p ${SNAP_COMMON}/ros2_ws
cp -r $SNAP/opt/ros/snap/share/rosbot_xl_description ${SNAP_COMMON}/ros2_ws/rosbot_xl_description
cp -r $SNAP/opt/ros/snap/share/ros_components_description ${SNAP_COMMON}/ros2_ws/ros_components_description

# copy DDS config files to shared folder
cp -r $SNAP/usr/share/rosbot-xl/config/*.xml ${SNAP_COMMON}/

# copy joy params
cp -r $SNAP/usr/share/rosbot-xl/config/teleop_twist_joy_params.yaml ${SNAP_COMMON}/

# copy webui layouts
cp -r $SNAP/usr/share/$SNAP_NAME/config/foxglove-*.json ${SNAP_COMMON}/