#!/bin/bash -e

# Define a function to log messages
source $SNAP/usr/bin/utils.sh

$SNAP/usr/bin/install_hook_ros.sh

# Parameters are 'unset'.
# Default configuration values is left to the launch file.
snapctl set driver.mecanum=True
snapctl set driver.include-camera-mount=True
snapctl set driver.camera-model=None
snapctl set driver.lidar-model=None
snapctl set driver.namespace! # unset

snapctl set webui.layout=default
snapctl set webui.port=8080

snapctl set serial-port="auto"

if ! snapctl is-connected raw-usb; then
  log "Plug 'raw-usb' isn't connected, please run:"
  log "sudo snap connect ${SNAP_NAME}:raw-usb"
fi

# copy meshes to shared folder
log "copy meshes to '${SNAP_COMMON}/ros2_ws/'"
mkdir -p ${SNAP_COMMON}/ros2_ws
cp -r $SNAP/opt/ros/snap/share/rosbot_xl_description ${SNAP_COMMON}/ros2_ws/rosbot_xl_description
cp -r $SNAP/opt/ros/snap/share/ros_components_description ${SNAP_COMMON}/ros2_ws/ros_components_description

# copy joy params
cp -r $SNAP/usr/share/rosbot-xl/config/teleop_twist_joy_params.yaml ${SNAP_COMMON}/

# copy webui layouts
cp -r $SNAP/usr/share/$SNAP_NAME/config/foxglove-*.json ${SNAP_COMMON}/